name: Unit tests
on:
  pull_request:
  push:
    branches:
    - qa/**
    - stable/**
jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    name: PHP 7.4
    env:
      COMPOSE_FILE: ${{ github.workspace }}/docker/docker-compose.dev.yml
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Increase virtual memory max_map_count
      run: sudo sysctl -w vm.max_map_count=262144
    - name: Start services
      run: docker-compose up -d percona elasticsearch
    - name: Setup PHP 7.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        coverage: none
        extensions: apcu
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache/files
        key: 20.04-7.4-composer-${{ hashFiles('composer.lock') }}
    - name: Install dependencies
      run: composer install
    - name: Copy config files
      run: |
        cp test/bootstrap/config.php config/config.php
        cp test/bootstrap/search.yml config/search.yml
        cp config/propel.ini.tmpl config/propel.ini
        cp apps/qubit/config/settings.yml.tmpl apps/qubit/config/settings.yml
    - name: Sleep for 10 seconds
      run: sleep 10
    - name: Initialize database and search index
      run: php symfony tools:purge --demo
    - name: Run tests
      run: composer test
